# SAM configuration file
version = 0.1

[default]
[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
stack_name = "crewai-course-generator-stack"
s3_bucket = ""  # SAM will create a deployment bucket
s3_prefix = "crewai-course-generator-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
resolve_image_repos = true
parameter_overrides = "ECRRepository=\"crewai-course-generator\" AccountId=\"746434296869\""
resolve_s3 = true
